swagger: "2.0"
info:
  version: "0.0.1"
  title: Secret Blog Api
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /auth:
    x-swagger-router-controller: users.find
    post:
      tags:
        - auth
      description: return user auth data
      operationId: postauth
      parameters:
        - name: User
          in: body
          description: auth properties
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Token"
        default:
          description: fallback error
          schema:
            $ref: "#/definitions/Response"
  /users:
    post:
      x-swagger-router-controller: users.add
      tags:
        - users
      description: add new user
      operationId: postuser
      parameters:
        - name: User
          in: body
          description: user properties
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Response"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Response"  
  /articles:
    post:
      x-swagger-router-controller: articles.add
      tags:
        - articles
      description: add article
      operationId: postarticle
      parameters:
        - name: "authorization"
          in: header
          description: auth headers
          required: true
          type: string
        - name: Articles
          in: body
          description: article properties
          required: true
          schema:
            $ref: "#/definitions/Articles"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Response"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Response"
    get:
      tags:
        - articles
      x-swagger-router-controller: articles.list
      description: return list of articles
      operationId: getarticles
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Articles"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Response"
  /articles/{id}:
    get:
      tags:
        - articles
      x-swagger-router-controller: articles.search
      description: return detail of searched article by id 
      operationId: getarticle
      parameters:
        - name: id
          in: path
          description: id of article
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Articles"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Response"
    put:
      tags:
        - articles
      x-swagger-router-controller: articles.update
      description: update info of specific article by id 
      operationId: putarticle
      parameters:
        - name: "authorization"
          in: header
          description: auth headers
          required: true
          type: string
        - name: id
          in: path
          description: id of article
          required: true
          type: string
        - name: Article
          in: body
          description: article properties
          required: false
          schema:
            $ref: "#/definitions/Articles"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Articles"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Response"
    delete:
      tags:
        - articles
      x-swagger-router-controller: articles.remove
      description: remove article by id 
      operationId: delarticle
      parameters:
        - name: "authorization"
          in: header
          description: auth headers
          required: true
          type: string
        - name: id
          in: path
          description: id of article
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Articles"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Response"
definitions:
  Response:
    required:
      - message
    properties:
      message:
        type: string
  User:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string
  Token:
    type: object
    properties:
      token:
        type: string
  Articles:
    type: object
    properties:
      title:
        type: string
      body:
        type: string
